// drastic_functions.h
// Auto-generated from drastic.cpp
// Generated by extract_functions.py

#ifndef DRASTIC_FUNCTIONS_H
#define DRASTIC_FUNCTIONS_H

//#include <stdio.h>
#include "drastic_val.h"

// SDL2
#include <SDL2/SDL.h>

#ifdef __cplusplus
extern "C" {
#endif

// ==================== 函数声明 ====================

// void __thiscall StringList:: AddString(StringList this, wchar_t param_1); // 注释掉，语法错误

int LZCOUNT(uint32_t x) {
    if (x == 0) return 32;
    
    int count = 0;
    if (x <= 0x0000FFFF) { count += 16; x <<= 16; }
    if (x <= 0x00FFFFFF) { count += 8;  x <<= 8;  }
    if (x <= 0x0FFFFFFF) { count += 4;  x <<= 4;  }
    if (x <= 0x3FFFFFFF) { count += 2;  x <<= 2;  }
    if (x <= 0x7FFFFFFF) { count += 1;  }
    return count;
}
// POPCOUNT - 计算字节中1的个数
#ifndef POPCOUNT
#define POPCOUNT(x) (__builtin_popcount((unsigned char)(x)))
#endif

// 通用位操作宏
#ifndef SUB164
#define SUB164(x, n) ((uint64_t)((x) >> (64 - (n))))
#endif

#ifndef ZEXT416
#define ZEXT416(x) ((uint32_t)((uint16_t)(x)))
#endif

// 其他可能需要的宏
#ifndef SEXT816
#define SEXT816(x) ((int16_t)((int8_t)(x)))
#endif

#ifndef ZEXT832
#define ZEXT832(x) ((uint32_t)((uint8_t)(x)))
#endif

undefined8 get_screen_ptr(uint param_1)

{
  long lVar1;
  
  //if (DAT_040315d4._4_4_ != 0) {
    return DAT_04031598;
  //}
  lVar1 = (ulong)(param_1 ^ (uint)DAT_040315cc) * 0x28;
  if ((&DAT_04031540)[lVar1] != '\0') {
    return *(undefined8 *)(&DAT_04031528 + lVar1);
  }
  return 0;
}
int get_screen_pitch(uint param_1)

{
  //if (DAT_040315d4._4_4_ == 0) {
    return (DAT_040315a8 +
           (uint)(byte)(&DAT_04031541)[(ulong)(param_1 ^ (uint)DAT_040315cc) * 0x28] * 3 *
           DAT_040315a8) * 0x100;
  //}
  return 0x640;
}

void apply_cycle_adjustment_hacks(long param_1);

void audio_buffer_force_feed(void);

undefined8 audio_buffer_state(void);

void audio_exit(long param_1);

char audio_pause(long param_1);

void audio_reset_buffer(void *param_1);

void audio_revert_pause_state(undefined8 param_1, int param_2);

void audio_sync(long param_1);

void audio_unpause(long param_1);

void backup_auto_save_step(long param_1);

void backup_data_store_savestate(long param_1, long param_2);

void backup_save(long param_1);

void backup_save_part_0(uint param_1);

void backup_store_savestate(long param_1, long param_2);

void benchmark_step(long param_1);


void blit_screen_menu(long param_1,ulong param_2,int param_3,uint param_4,int param_5)

{
  uint uVar1;
  long lVar2;
  ulong uVar3;
  undefined2 *puVar4;
  undefined2 *puVar5;
  uint uVar6;
  uint uVar7;
  int iVar8;
  ulong uVar9;
  
  lVar2 = get_screen_ptr(0);
  uVar3 = get_screen_pitch(0);
  uVar6 = (uint)(uVar3 >> 1) & 0x7fffffff;
  puVar5 = (undefined2 *)(lVar2 + ((ulong)(uVar6 * param_3) + (param_2 & 0xffffffff)) * 2);
  if (param_5 != 0) {
    uVar9 = 0;
    iVar8 = 0;
    uVar3 = uVar9;
    uVar7 = param_4;
    puVar4 = puVar5;
    if (param_4 != 0) {
      do {
        do {
          *puVar5 = *(undefined2 *)(param_1 + uVar9 * 2);
          uVar1 = (int)uVar9 + 1;
          uVar9 = (ulong)uVar1;
          puVar5 = puVar5 + 1;
        } while (uVar1 != uVar7);
        iVar8 = iVar8 + 1;
        puVar5 = (undefined2 *)((long)puVar4 + (ulong)(uVar6 << 1));
        uVar9 = (ulong)((int)uVar3 + param_4);
        uVar7 = uVar7 + param_4;
        uVar3 = uVar9;
        puVar4 = puVar5;
      } while (param_5 != iVar8);
    }
  }
  return;
}

bool Buf_Create(long param_1, long param_2, undefined8 param_3);

void Buf_Free(undefined8 param_1, long param_2);

void Buf_Init(undefined8 param_1);

#ifdef __GLIBC__
// 系统已经定义了 chdir，使用系统版本
// int chdir(char* __path); // 注释掉，避免冲突
#else
int chdir(char* __path);
#endif // __GLIBC__

void chomp_whitespace(char param_1);

void clear_gui_actions(void);

void clear_screen(void);

void clear_screen_menu(undefined2 param_1)

{
  undefined8 *puVar1;
  ulong uVar2;
  undefined8 *puVar3;
  undefined8 *puVar4;
  int iVar5;
  undefined8 *puVar6;
  
  puVar1 = (undefined8 *)get_screen_ptr(0);
  uVar2 = get_screen_pitch(0);
  puVar4 = puVar1 + 200;
  iVar5 = 0x1e0;
  puVar6 = puVar1;
  do {
    do {
      puVar3 = puVar1 + 2;
      puVar1[1] = CONCAT26(param_1,CONCAT24(param_1,CONCAT22(param_1,param_1)));
      *puVar1 = CONCAT26(param_1,CONCAT24(param_1,CONCAT22(param_1,param_1)));
      puVar1 = puVar3;
    } while (puVar4 != puVar3);
    puVar1 = (undefined8 *)((long)puVar6 + (uVar2 & 0xfffffffe));
    puVar4 = (undefined8 *)((long)puVar4 + (uVar2 & 0xfffffffe));
    iVar5 = iVar5 + -1;
    puVar6 = puVar1;
  } while (iVar5 != 0);
  return;
}

int close(int __fd);

#ifdef __GLIBC__
// 系统已经定义了 closedir，使用系统版本
// int closedir(DIR __dirp); // 注释掉，避免冲突（系统版本使用 DIR*）
#else
int closedir(DIR __dirp);
#endif // __GLIBC__

void config_default(undefined4 param_1);

void config_update_settings(long param_1);

static inline ulong convert_thumb_instruction_to_arm(ulong param_1,undefined4 *param_2);

void convert_touch_coordinates(int param_1, int param_2, uint param_3, uint param_4, int param_5);

int compare_directory_names(undefined8 *param_1,undefined8 *param_2)
{
  int iVar1 = 0;
  
  if (*(char *)*param_2 == '.') {
    return 1;
  }
  if (*(char *)*param_1 != '.') {
    iVar1 = strcasecmp((char *)*param_1,(char *)*param_2);
    return iVar1;
  }
  return -1;
}

int compare_file_names(undefined8 *param_1,undefined8 *param_2)

{
  int iVar1;
  char *__s1;
  char *__s2;
  
  __s1 = (char *)param_1[1];
  __s2 = (char *)param_2[1];
  if (__s1 == (char *)0x0 && __s2 != (char *)0x0) {
    return -1;
  }
  if (__s2 == (char *)0x0 && __s1 != (char *)0x0) {
    return 1;
  }
  if (__s1 == (char *)0x0) {
    __s1 = (char *)*param_1;
  }
  if (__s2 == (char *)0x0) {
    iVar1 = strcasecmp(__s1,(char *)*param_2);
    return iVar1;
  }
  iVar1 = strcasecmp(__s1,__s2);
  return iVar1;
}

void coprocessor_store_savestate(long param_1, long param_2);

ulong cpu_block_check_allocation16(long param_1, uint param_2);

undefined8 cpu_block_check_allocation32(long param_1, ulong param_2);

ulong cpu_block_check_allocation8(long param_1, uint param_2);

undefined8 cpu_block_create(long param_1, uint param_2, uint param_3);

void cpu_block_fill_allocation(long param_1, uint param_2, int param_3);

void cpu_block_flush(long param_1, uint param_2);

void cpu_block_load_pc(long param_1);

void cpu_block_log_all(long param_1, char param_2);

void cpu_block_log_from_hash(long param_1, long param_2, ulong param_3, undefined8 param_4);

long cpu_block_lookup_base(long param_1, ulong param_2);

long cpu_block_lookup_recursive(long param_1, uint param_2);

undefined8 cpu_block_modify_itcm(long param_1, ulong param_2);

void cpu_next_action_arm7_to_event_update(long param_1);

int cpu_print_profiler_results(void);

void cpu_store_savestate(long param_1, long param_2);

void cpu_translate_alu_op_imm(long param_1, uint param_2);

int * cpu_translate_block(long param_1, long param_2, uint param_3, uint param_4);

void cpu_translate_block_memory_op(uint param_1, uint param_2);

void cpu_translate_bx_op(long param_1, uint param_2);

void cpu_translate_direct_link(long param_1);

undefined4 cpu_translate_imm_map_to_logical_isra_0_part_0(ulong param_1, uint param_2, uint param_3);

void cpu_translate_instruction(long param_1);

void cpu_translate_link_delayed_targets(long param_1);

void cpu_translate_log_block(long param_1, FILE* param_2, undefined4 param_3);

void cpu_translate_log_translated_code(undefined8 param_1, undefined4 param_2, undefined4 param_3);

ulong cpu_translate_map_src_reg_part_0(long param_1, uint param_2);

void cpu_translate_mrs_op(long param_1, ulong param_2);

void cpu_translate_msr_op(long param_1, ulong param_2);

void cpu_translate_raise_exception(long param_1, int param_2, uint param_3);

void cpu_translate_set_imm32_isra_0(undefined8 param_1, uint param_2, ulong param_3);

void cpu_translate_store_pc_metadata(long param_1, int param_2);

uint CrcCalc(undefined8 param_1, undefined8 param_2);

void CrcGenerateTable(void);

undefined8 * create_menu_controls(long param_1, undefined8 param_2);

undefined8 * create_menu_extra_controls(long param_1, undefined8 param_2, undefined8 param_3);

undefined8 * create_menu_firmware(long param_1, undefined8 param_2);

undefined8 * create_menu_main(long param_1);

undefined8 * create_menu_options(long param_1, undefined8 param_2);

undefined8 * create_menu_video_options(long param_1, undefined8 param_2, undefined8 param_3);

#ifdef __GLIBC__
// 系统已经定义了 ctime，使用系统版本
// char * ctime(time_t __timer); // 注释掉，避免冲突
#else
char * ctime(time_t __timer);
#endif // __GLIBC__

void delay_us(ulong param_1);

void disasm_arm64_instruction(uint param_1, char param_2, long param_3, long param_4, int param_5);

void disasm_arm_data_proc(ulong param_1, undefined8 param_2, undefined8 param_3);

void disasm_arm_instruction(ulong param_1, char param_2, int param_3, ulong param_4, int param_5);

void disasm_arm_mem_reg_operand2(ulong param_1, char param_2);

void disasm_arm_memory_transfer(ulong param_1, undefined8 param_2, undefined8 param_3);

void disasm_arm_memory_transfer2(uint param_1, undefined8 param_2, undefined8 param_3);

void disasm_arm_reg_operand2(ulong param_1, char param_2);

void disasm_thumb_instruction(ulong param_1, char param_2, int param_3);

void dma_store_savestate(long param_1, long param_2, uint param_3);

uint dma_transfer(long param_1, long param_2);

long dma_transfer_display(undefined8 param_1, long param_2, int param_3);

void dma_transfer_gxfifo(long param_1, long param_2);

void draw_menu_bg(undefined8 param_1);


void escape_str(byte *param_1,byte *param_2)

{
  byte bVar1;
  byte *pbVar2;
  
  bVar1 = *param_2;
  do {
    while( true ) {
      if (bVar1 == 0) {
        *param_1 = 0;
        return;
      }
      if (bVar1 != 0x27) break;
      param_1[0] = 0x26;
      param_1[1] = 0x61;
      param_1[2] = 0x70;
      param_1[3] = 0x6f;
      pbVar2 = param_1 + 6;
      param_1[3] = 0x6f;
      param_1[4] = 0x73;
      param_1[5] = 0x3b;
      param_1[6] = 0;
LAB_00172ac8:
      param_2 = param_2 + 1;
      bVar1 = *param_2;
      param_1 = pbVar2;
    }
    if (bVar1 < 0x28) {
      if (bVar1 == 0x22) {
        param_1[0] = 0x26;
        param_1[1] = 0x71;
        param_1[2] = 0x75;
        param_1[3] = 0x6f;
        pbVar2 = param_1 + 5;
        param_1[3] = 0x6f;
        param_1[4] = 0x74;
        param_1[5] = 0x3b;
        param_1[6] = 0;
      }
      else {
        if (bVar1 != 0x26) goto LAB_00172b24;
        pbVar2 = param_1 + 5;
        param_1[0] = 0x26;
        param_1[1] = 0x61;
        param_1[2] = 0x6d;
        param_1[3] = 0x70;
        param_1[4] = 0x3b;
        param_1[5] = 0;
      }
      goto LAB_00172ac8;
    }
    if (bVar1 == 0x3c) {
      param_1[0] = 0x26;
      param_1[1] = 0x6c;
      param_1[2] = 0x74;
      param_1[3] = 0x3b;
      pbVar2 = param_1 + 4;
      *pbVar2 = 0;
      goto LAB_00172ac8;
    }
    if (bVar1 != 0x3e) {
LAB_00172b24:
      pbVar2 = param_1 + 1;
      *param_1 = bVar1;
      goto LAB_00172ac8;
    }
    param_1[0] = 0x26;
    param_1[1] = 0x67;
    param_1[2] = 0x74;
    param_1[3] = 0x3b;
    param_1 = param_1 + 4;
    *param_1 = 0;
    param_2 = param_2 + 1;
    bVar1 = *param_2;
  } while( true );
}

void event_force_task_switch_function(long param_1);

void execute_cpu(long param_1);

void event_list_store_savestate(long param_1, long param_2);

void event_scanline_start_function(long* param_1);

void execute_arm_raise_interrupt(long param_1);

void execute_events(long param_1);

void exit(int __status);

void extended_store16(long param_1, ulong param_2, undefined2 param_3);

void extended_store32(long param_1, ulong param_2, undefined4 param_3);

void extended_store8(long param_1, ulong param_2, undefined1 param_3);

int fclose(FILE* __stream);

int fflush(FILE* __stream);

char * fgets(char* __s, int __n, FILE* __stream);

int File_Close(undefined8 param_1);

void File_Construct(undefined8 param_1);

undefined8 file_info_cache_load(long param_1);

void FileInStream_CreateVTable(undefined8 param_1);

int fileno(FILE* __stream);

void FileOutStream_CreateVTable(undefined8 param_1);


void fill_screen_menu(undefined2 param_1,ulong param_2,int param_3,uint param_4,int param_5)

{
  int iVar1;
  long lVar2;
  ulong uVar3;
  undefined8 *puVar4;
  undefined8 *puVar6;
  int iVar7;
  uint uVar8;
  undefined8 *puVar5;
  
  lVar2 = get_screen_ptr(0);
  uVar3 = get_screen_pitch(0);
  uVar8 = (uint)(uVar3 >> 1) & 0x7fffffff;
  puVar6 = (undefined8 *)(lVar2 + ((ulong)(uVar8 * param_3) + (param_2 & 0xffffffff)) * 2);
  if (param_5 != 0) {
    if (param_4 != 0) {
      iVar7 = 0;
      do {
        puVar4 = puVar6;
        if (param_4 - 1 < 7) {
          uVar3 = 0;
LAB_001884d0:
          iVar1 = (int)uVar3;
          *(undefined2 *)((long)puVar6 + uVar3 * 2) = param_1;
          if (iVar1 + 1U < param_4) {
            *(undefined2 *)((long)puVar6 + (ulong)(iVar1 + 1U) * 2) = param_1;
            if (iVar1 + 2U < param_4) {
              *(undefined2 *)((long)puVar6 + (ulong)(iVar1 + 2U) * 2) = param_1;
              if (iVar1 + 3U < param_4) {
                *(undefined2 *)((long)puVar6 + (ulong)(iVar1 + 3U) * 2) = param_1;
                if (iVar1 + 4U < param_4) {
                  *(undefined2 *)((long)puVar6 + (ulong)(iVar1 + 4U) * 2) = param_1;
                  if (iVar1 + 5U < param_4) {
                    *(undefined2 *)((long)puVar6 + (ulong)(iVar1 + 5U) * 2) = param_1;
                    if (iVar1 + 6U < param_4) {
                      *(undefined2 *)((long)puVar6 + (ulong)(iVar1 + 6U) * 2) = param_1;
                    }
                  }
                }
              }
            }
          }
        }
        else {
          do {
            puVar5 = puVar4 + 2;
            puVar4[1] = CONCAT26(param_1,CONCAT24(param_1,CONCAT22(param_1,param_1)));
            *puVar4 = CONCAT26(param_1,CONCAT24(param_1,CONCAT22(param_1,param_1)));
            puVar4 = puVar5;
          } while (puVar5 != puVar6 + ((ulong)((param_4 >> 3) - 1) + 1) * 2);
          if (param_4 != (param_4 & 0xfffffff8)) {
            uVar3 = (ulong)(param_4 & 0xfffffff8);
            goto LAB_001884d0;
          }
        }
        iVar7 = iVar7 + 1;
        puVar6 = (undefined8 *)((long)puVar6 + (ulong)(uVar8 << 1));
      } while (param_5 != iVar7);
    }
  }
  return;
}


#ifdef __GLIBC__
// 系统已经定义了 fopen 和 fopen64，使用系统版本
// FILE * fopen(char* __filename, char* __modes); // 注释掉，避免冲突
// FILE * fopen64(char* __filename, char* __modes); // 注释掉，避免冲突
#else
FILE * fopen(char* __filename, char* __modes);

FILE * fopen64(char* __filename, char* __modes);
#endif // __GLIBC__

int fputc(int __c, FILE* __stream);

size_t fread(void* __ptr, size_t __size, size_t __n, FILE* __stream);

void free(void* __ptr);

int fseek(FILE* __stream, long __off, int __whence);

long ftell(FILE* __stream);

int ftruncate(int __fd, __off_t __length);

#ifdef __GLIBC__
// 系统已经定义了 fwrite，使用系统版本
// size_t fwrite(void* __ptr, size_t __size, size_t __n, FILE* __s); // 注释掉，避免冲突
#else
size_t fwrite(void* __ptr, size_t __size, size_t __n, FILE* __s);
#endif // __GLIBC__

uint game_database_generate_crc32_from_memory(byte param_1, uint param_2);

long game_database_lookup_by_crc32(long param_1, uint param_2);


long game_database_lookup_by_game_code(long *param_1,uint param_2,char *param_3)

{
  uint uVar1;
  uint uVar2;
  uint uVar3;
  int iVar4;
  ulong uVar5;
  ulong uVar6;
  ulong uVar7;
  long lVar8;
  int iVar9;
  long lVar10;
  long lVar11;
  
  uVar2 = *(uint *)(param_1 + 4);
  uVar5 = (ulong)uVar2;
  lVar8 = param_1[2];
  uVar6 = 0;
  while (uVar6 < uVar5) {
    while( true ) {
      uVar7 = uVar5 + uVar6 >> 1;
      uVar3 = *(uint *)(*(long *)(lVar8 + uVar7 * 8) + 0x24);
      if (param_2 == uVar3) {
        lVar10 = (long)(int)uVar7;
        iVar9 = (int)((long)(uVar7 * 8) >> 3);
        iVar4 = iVar9;
        goto joined_r0x0017414c;
      }
      if (uVar3 <= param_2) break;
      uVar5 = uVar7;
      if (uVar7 <= uVar6) goto LAB_001740c8;
    }
    uVar6 = uVar7 + 1;
  }
LAB_001740c8:
  if (uVar2 == 0) {
    return 0;
  }
LAB_001740cc:
  lVar8 = 0;
  uVar3 = 0;
  do {
    uVar3 = uVar3 + 1;
    if (((*(uint *)(*param_1 + 0x24 + lVar8) ^ param_2) & 0xffffff) == 0) {
      printf(
                   " Couldn\'t find full gamecode (%08x), going with first alt-region match (%08x)\n"
                   ,param_2);
      return *param_1 + lVar8;
    }
    lVar8 = lVar8 + 0x38;
  } while (uVar3 < uVar2);
  return 0;
joined_r0x0017414c:
  if (iVar4 < 0) goto LAB_0017417c;
  lVar11 = *(long *)(lVar8 + lVar10 * 8);
  lVar10 = lVar10 + -1;
  if (*(uint *)(lVar11 + 0x24) != uVar3) goto LAB_0017417c;
  iVar4 = strcmp((char *)(lVar11 + 8),param_3);
  if (iVar4 == 0) {
    return lVar11;
  }
  iVar4 = (int)lVar10;
  goto joined_r0x0017414c;
LAB_0017417c:
  uVar1 = iVar9 + 1;
  if (uVar1 < uVar2) {
    lVar10 = (long)(int)uVar1;
    do {
      lVar11 = *(long *)(lVar8 + lVar10 * 8);
      lVar10 = lVar10 + 1;
      if (*(uint *)(lVar11 + 0x24) != uVar3) {
        printf(
                     " Couldn\'t find gamecode + ID for %08x:%s, returning first gamecode match.\n",
                     uVar3,param_3);
        return *(long *)(lVar8 + uVar7 * 8);
      }
      iVar4 = strcmp((char *)(lVar11 + 8),param_3);
      if (iVar4 == 0) {
        return lVar11;
      }
    } while ((uint)lVar10 < uVar2);
    goto LAB_001740cc;
  }
  goto LAB_001740c8;
}

void gamecard_apply_keycode(undefined8 param_1, long param_2);

int gamecard_close(long param_1);

undefined8
nds_file_read_to_memory_partial(char *param_1,char *param_2,void *param_3,uint param_4,uint param_5)

{
  int iVar1;
  char *__s1;
  FILE *__stream;
  long lVar2;
  size_t sVar3;
  undefined8 uVar4;
  ulong __n;
  
  __n = (ulong)param_4;
  __s1 = strrchr(param_1,0x2e);
  if (__s1 != (char *)0x0) {
    iVar1 = strcasecmp(__s1,".nds");
    if (iVar1 == 0) {
      if (param_3 == (void *)0x0 || param_4 == 0) {
        return 0;
      }
      __stream = fopen(param_1,"rb");
      if (__stream != (FILE *)0x0) {
        fseek(__stream,0,2);
        lVar2 = ftell(__stream);
        *param_2 = (uint)lVar2;
        fseek(__stream,(ulong)param_5,0);
        if (*param_2 < param_4 + param_5) {
          fclose(__stream);
          return 0xffffffff;
        }
        sVar3 = fread(param_3,1,__n,__stream);
        if (__n == sVar3) {
          fclose(__stream);
          return 0;
        }
        fclose(__stream);
        return 0xffffffff;
      }
    }
  }
  return 0xffffffff;
}

void gamecard_database_entry_for_file(undefined8 param_1,undefined8 param_2)

{
  int iVar1;
  undefined8 uVar2;
  char *pcVar3;
  undefined1 auStack_21c [4];
  char acStack_218 [12];
  undefined1 local_20c;
  char acStack_208 [12];
  undefined4 local_1fc;
  long local_8;
  
  local_8 = __stack_chk_guard;
  iVar1 = nds_file_read_to_memory_partial(param_2,auStack_21c,acStack_208,0x20,0);
  uVar2 = 0;
  if (-1 < iVar1) {
    pcVar3 = strncpy(acStack_218,acStack_208,0xc);
    local_20c = 0;
    uVar2 = game_database_lookup_by_game_code(param_1,local_1fc,pcVar3);
  }
  if (local_8 - __stack_chk_guard == 0) {
    return;
  }
                    // WARNING: Subroutine does not return
  //__stack_chk_fail(uVar2,local_8 - ___stack_chk_guard,0);
}

void gamecard_decrypt_pair(uint param_1, uint param_2);

void gamecard_decrypt_secure_region(long param_1, uint param_2, void* param_3);

void gamecard_encrypt_pair(uint param_1, uint param_2);

void gamecard_initialize_homebrew(long param_1);

void gamecard_load_gba(long param_1, undefined8 param_2);

undefined8 gamecard_load_program(long param_1);

void gamecard_store_savestate(long param_1, long param_2, uint param_3);

char * gba_backup_auto_save_step(char param_1);

void gba_scan_save(long param_1);

void geometry_backface_test_single(int param_1, uint param_2, char param_3);

void geometry_backface_test_single_constprop_0(int param_1, char param_2);

void geometry_clipped_vertex_interpolate_edge(int param_1, int param_2, int param_3, ulong param_4);

void geometry_flush_polygons(long param_1);

void geometry_matrix_multiply_4x4_by_4x4_asm(undefined4 param_1, int param_2, int param_3);

void geometry_perspective_apply_hires_asm(long param_1, undefined8 param_2, uint param_3);

void geometry_perspective_apply_normal_asm(long param_1, undefined8 param_2, uint param_3);

void geometry_store_savestate(long param_1, long param_2, uint param_3);

void geometry_submit_polygons_constprop_2(long param_1, uint param_2, int param_3);

void geometry_submit_polygons_constprop_3(long param_1, uint param_2, int param_3);

void geometry_submit_vertexes(long param_1, ulong param_2, uint param_3);

void geometry_transform_vertex_block_asm(int param_1);

void geometry_transform_vertexes(long param_1);

uint get_gui_input(long param_1, uint param_2);

void get_rlist(uint param_1, undefined1 param_2);

undefined4 get_screen_bytes_per_pixel(void);

undefined1 get_screen_hires_mode(uint param_1);

//int get_screen_pitch(uint param_1);

//undefined8 get_screen_ptr(uint param_1);

void get_ticks_us(long param_1);

char * getcwd(char* __buf, size_t __size);

int getopt_long(int argc, char* const argv[], const char* optstring, const struct option* longopts, int* longindex);

int getpagesize(void);

int gettimeofday(timeval __tv, __timezone_ptr_t __tz);


void * icon_cache_add(long *param_1,FILE *param_2,void *param_3,char *param_4)

{
  uint uVar1;
  uint uVar2;
  size_t sVar3;
  void *pvVar4;
  char *__dest;
  uint __c;
  long lVar5;
  
  uVar2 = *(uint *)(param_1 + 3);
  uVar1 = uVar2 + 1;
  sVar3 = strlen(param_4);
  printf("Adding icon to cache @ %d (%p)\n",uVar2,param_2);
  pvVar4 = realloc((void *)*param_1,(ulong)uVar1 * 800);
  *param_1 = (long)pvVar4;
  pvVar4 = realloc((void *)param_1[1],(ulong)uVar1 << 3);
  param_1[1] = (long)pvVar4;
  pvVar4 = (void *)(*param_1 + (ulong)uVar2 * 800);
  memcpy(pvVar4,param_3,800);
  lVar5 = param_1[1];
  __c = (uint)sVar3;
  __dest = malloc((ulong)(__c + 1));
  *(char **)(lVar5 + (ulong)uVar2 * 8) = __dest;
  strcpy(__dest,param_4);
  *(uint *)(param_1 + 3) = uVar1;
  if (param_2 != (FILE *)0x0) {
    fwrite(param_3,0x200,1,param_2);
    fwrite((void *)((long)param_3 + 0x200),0x20,1,param_2);
    fputc(__c,param_2);
    fputc(__c >> 8,param_2);
    fwrite(param_4,sVar3 & 0xffffffff,1,param_2);
  }
  return pvVar4;
}

undefined8 icon_cache_load(long param_1);

int InFile_Open(undefined8 param_1, char param_2);

void inflate(void);

void inflateEnd(void);

void inflateInit2_(void);

undefined8 initialize_audio(long param_1);

void initialize_backup(void* param_1, int param_2, void* param_3, uint param_4, char param_5);

void initialize_coprocessor(long param_1, long param_2);

void initialize_dma(long param_1, long param_2, long param_3, long param_4, long param_5);

void initialize_cpu(long param_1, long param_2, int param_3, long param_4);

void initialize_debug(undefined8 param_1, undefined8 param_2);

void initialize_event(long param_1, uint param_2, undefined8 param_3, undefined8 param_4);

void initialize_event_list(long param_1, long param_2);

undefined4 initialize_game_database(undefined8 param_1, char param_2);

void initialize_gamecard(long param_1, long param_2);

void initialize_geometry(long param_1, undefined8 param_2, undefined8 param_3);

void initialize_input(long param_1, undefined8 param_2);

void initialize_ipc(long param_1, long param_2, long param_3);

undefined8 initialize_lua(long param_1);

void initialize_memory(long param_1, long param_2);

void initialize_memory_map_arm7(undefined8 param_1);

void initialize_memory_map_arm9(undefined8 param_1);

void initialize_rtc(undefined8 param_1, undefined8 param_2);

void initialize_screen(uint param_1);

void initialize_spi_peripherals(long param_1, long param_2);

void initialize_spu(long param_1, long param_2);

void initialize_system(long param_1);

void initialize_system_directories(undefined8 param_1);

void initialize_system_directory(long param_1, undefined8 param_2);

void initialize_texture_cache(undefined8 param_1, undefined8 param_2);

int initialize_translation_cache(void* param_1);

void initialize_video(long param_1, long param_2);

void initialize_video_2d(long param_1, uint param_2, long param_3);

int initialize_video_3d(void* param_1);

ulong input_log_close(long param_1);

void input_log_playback(void* param_1, char param_2);

void input_log_record(long param_1, char param_2);

void ipc_store_savestate(long param_1, long param_2);

undefined8 load_cheat_directory(long param_1, char param_2);

undefined8 load_cheat_listing(char param_1, undefined4 param_2, undefined4 param_3);

undefined8 load_config_file(long param_1,undefined8 param_2,undefined4 param_3);

undefined8 load_config_file_binary(long param_1, undefined8 param_2, int param_3);

void load_custom_cheats(long param_1, long param_2);

undefined8 load_directory_config_file(long param_1, undefined8 param_2);

int load_file(long param_1, long param_2, char param_3);

void load_logo(long param_1);

ulong load_memory16(long param_1, ulong param_2);

ulong load_memory32(long param_1, ulong param_2);

ulong load_memory8(long param_1, ulong param_2);

undefined4 load_nds(long param_1, char* param_2);

int load_system_file(long param_1, undefined8 param_2, void* param_3, int param_4);

void LookInStream_Read(long param_1, long param_2, long param_3);

void LookInStream_Read2(long param_1, long param_2, long param_3, uint param_4);

void LookInStream_SeekTo(long param_1, undefined8 param_2);

void LookToRead_CreateVTable(undefined8 param_1, int param_2);

void LookToRead_Init(long param_1);

uint * lookup_cheat_entry(long param_1, uint param_2, uint param_3);

__off_t lseek(int __fd, __off_t __offset, int __whence);

__off64_t lseek64(int __fd, __off64_t __offset, int __whence);

bool lua_is_active(void);

undefined4 lua_load_script(long param_1);

void lua_on_frame_update(void);

void lua_on_load_game(undefined8 param_1);

void Lzma2Dec_Allocate(undefined8 param_1, uint param_2, undefined8 param_3);

void Lzma2Dec_Init(long param_1);

undefined8 LzmaDec_Allocate(uint param_1, byte param_2, uint param_3, undefined8 param_4);

void LzmaDec_Free(long param_1, long param_2);

void LzmaDec_Init(long param_1);

int Lzma2Dec_DecodeToBuf
              (uint *param_1,void *param_2,ulong *param_3,byte *param_4,ulong *param_5,int param_6,
              int *param_7);

void * malloc(size_t __size);

void map_cartridge_region_gba(undefined8 param_1, long param_2, long param_3, uint param_4);

void map_cartridge_region_motion(undefined8 param_1, long param_2);

void map_cartridge_region_motion_hb(undefined8 param_1, long param_2);

void map_memory_page_from_memory_map(long param_1, ulong param_2);

void map_vram_page_region_arm9(long param_1, long param_2, uint param_3, uint param_4, uint param_5);

#ifdef __GLIBC__
// 系统已经定义了 mbstowcs，使用系统版本
// size_t mbstowcs(wchar_t __pwcs, char* __s, size_t __n); // 注释掉，避免冲突
#else
size_t mbstowcs(wchar_t __pwcs, char* __s, size_t __n);
#endif // __GLIBC__

void memalign(void);

#ifdef __GLIBC__
// 系统已经定义了这些函数，使用系统版本
// int memcmp(void* __s1, void* __s2, size_t __n); // 注释掉，避免冲突
// void * memcpy(void* __dest, void* __src, size_t __n); // 注释掉，避免冲突
// void * memmem(void* __haystack, size_t __haystacklen, void* __needle, size_t __needlelen); // 注释掉，避免冲突
#else
int memcmp(void* __s1, void* __s2, size_t __n);

void * memcpy(void* __dest, void* __src, size_t __n);

void * memmem(void* __haystack, size_t __haystacklen, void* __needle, size_t __needlelen);
#endif // __GLIBC__
uint memory_region_block_memory_load(long param_1,undefined8 param_2,uint param_3,undefined4 *param_4,uint param_5);
uint memory_check_code_region(uint param_1, uint param_2, ulong param_3, int param_4);

void memory_clear_slot2(long param_1);

void memory_copy_nintendo_logo(long param_1, long param_2);

undefined8 memory_setup_slot2_gba(long param_1, undefined8 param_2, undefined4 param_3);

undefined8 memory_setup_slot2_motion(long param_1);

undefined8 memory_setup_slot2_motion_hb(long param_1);

undefined8 memory_setup_slot2_ram(long param_1);

undefined8 memory_setup_slot2_rumble(long param_1);

void memory_store_savestate(undefined8 param_1, long param_2, uint param_3);

void * memset(void* __s, int __c, size_t __n);

void menu(long param_1, int param_2);

void menu_bios_warning(long param_1);

#ifdef __GLIBC__
// 系统已经定义了 mkdir，使用系统版本
// int mkdir(char* __path, __mode_t __mode); // 注释掉，避免冲突
#else
int mkdir(char* __path, __mode_t __mode);
#endif // __GLIBC__

void * mmap(void* __addr, size_t __len, int __prot, int __flags, int __fd, __off_t __offset);

void * mmap64(void* __addr, size_t __len, int __prot, int __flags, int __fd, __off64_t __offset);

void motion_pack_hb_set_acceleration(float param_1, float param_2, float param_3, long param_4);

void motion_pack_hb_set_gyroscope(float param_1, long param_2);

void motion_pack_set_acceleration(float param_1, float param_2, float param_3, long param_4);

int mprotect(void* __addr, size_t __len, int __prot);

int munmap(void* __addr, size_t __len);

void nds_file_close(int *param_1);

undefined4 nds_file_get_icon_data(char *param_1,undefined4 *param_2)

{
  uint uVar1;
  undefined4 uVar2;
  uint uVar3;
  int iVar4;
  undefined4 *puVar5;
  uint uVar6;
  undefined4 uVar7;
  undefined1 auStack_44c [4];
  undefined1 auStack_448 [32];
  undefined4 auStack_428 [8];
  undefined4 auStack_408 [8];
  undefined4 auStack_3e8 [8];
  undefined4 auStack_3c8 [104];
  undefined8 local_228;
  undefined8 uStack_220;
  undefined8 local_218;
  undefined8 uStack_210;
  undefined1 auStack_108 [256];
  long local_8;
  
  local_8 = __stack_chk_guard;
  iVar4 = nds_file_read_to_memory_partial(param_1,auStack_44c,auStack_448,0x80,0);
  if (iVar4 == 0) {
    iVar4 = nds_file_read_to_memory_partial(param_1,auStack_44c,auStack_448,0x440,auStack_3e8[2]);
    if (iVar4 == 0) {
      *(undefined8 *)(param_2 + 0x80) = local_228;
      *(undefined8 *)(param_2 + 0x82) = uStack_220;
      *(undefined8 *)(param_2 + 0x84) = local_218;
      *(undefined8 *)(param_2 + 0x86) = uStack_210;
      memcpy(param_2 + 0x88,auStack_108,0x100);
      uVar6 = 0;
      puVar5 = param_2;
      do {
        uVar1 = uVar6 & 7;
        uVar3 = uVar6 >> 3;
        uVar6 = uVar6 + 1;
        uVar1 = uVar1 + uVar3 * 0x20;
        uVar7 = auStack_408[uVar1];
        uVar2 = auStack_3c8[uVar1];
        *puVar5 = auStack_428[uVar1];
        puVar5[1] = uVar7;
        puVar5[2] = auStack_3e8[uVar1];
        puVar5[3] = uVar2;
        puVar5 = puVar5 + 4;
      } while (uVar6 != 0x20);
      *(undefined2 *)(param_2 + 0x80) = 0;
      uVar7 = 0;
      goto LAB_00176468;
    }
  }
  uVar7 = 0xffffffff;
LAB_00176468:
  if (local_8 - __stack_chk_guard == 0) {
    return uVar7;
  }
                    // WARNING: Subroutine does not return
  //__stack_chk_fail();
}

long * nds_file_open(char* param_1, long param_2, int param_3, int param_4);

undefined8 nds_file_open_cached(long param_1, undefined8 param_2, int param_3, int param_4);

int open(char* __file, int __oflag, ...);

int open64(char* __file, int __oflag, ...);

#ifdef __GLIBC__
// 系统已经定义了 opendir，使用系统版本
// DIR * opendir(char* __name); // 注释掉，避免冲突
#else
DIR * opendir(char* __name);
#endif // __GLIBC__

void operator_delete(void* param_1, ulong param_2);

void * operator_new(ulong param_1);

int OutFile_Open(undefined8 param_1, char param_2);

void patch_firmware_header_data(long param_1);

void patch_firmware_user_data(wchar_t param_1, long param_2);

#ifdef __GLIBC__
// 系统已经定义了 perror，使用系统版本
// void perror(char* __s); // 注释掉，避免冲突
#else
void perror(char* __s);
#endif // __GLIBC__

void platform_get_input(long param_1);

void platform_initialize(void);

int get_screen_pitch_text(uint param_1)

{
  //if (DAT_040315d4._4_4_ == 0) {
    return (DAT_040315a8 +
           (uint)(byte)(&DAT_04031541)[(ulong)(param_1 ^ (uint)DAT_040315cc) * 0x28] * DAT_040315a8)
           * 0x100;
  //}
  return 0x640;
}

void print_string_ext(byte *param_1,ulong param_2,ulong param_3,int param_4,int param_5,long param_6
                     ,long param_7,ulong param_8,uint param_9)

{
  int iVar1;
  uint uVar2;
  int iVar3;
  int iVar4;
  ushort uVar5;
  undefined2 uVar6;
  undefined *puVar7;
  int iVar8;
  uint uVar9;
  uint uVar10;
  uint uVar11;
  int iVar12;
  int iVar13;
  ulong uVar14;
  uint uVar15;
  ulong uVar16;
  
  iVar8 = get_screen_bytes_per_pixel();
  puVar7 = current_font;
  if (iVar8 == 2) {
    uVar9 = (uint)*param_1;
    if (*param_1 != 0) {
      iVar3 = (int)((param_8 & 0xffffffff) >> 1);
      iVar4 = *(int *)(current_font + 4);
      uVar15 = 0;
      uVar16 = 1;
      iVar8 = param_4;
      do {
        if (uVar9 != 10) goto LAB_00187de8;
        param_5 = param_5 + iVar4;
        iVar8 = param_4;
LAB_00187dd0:
        uVar9 = (uint)param_1[uVar16];
        uVar15 = uVar15 + 1;
        if (uVar9 == 0 && uVar15 < param_9) {
          uVar9 = 0x20;
LAB_00187de8:
          iVar12 = *(int *)puVar7;
          iVar8 = iVar8 + iVar12;
          uVar9 = *(uint *)(puVar7 + (long)(int)uVar9 * 4 + 0x2008);
          uVar10 = iVar8 + iVar3 * param_5;
          uVar11 = uVar9 + iVar4;
          if (iVar4 != 0) {
            do {
              while( true ) {
                uVar14 = (ulong)(uVar10 - iVar12);
                uVar5 = *(ushort *)(puVar7 + (ulong)uVar9 * 2 + 8);
                if (iVar12 != 0) break;
LAB_00187e58:
                uVar9 = uVar9 + 1;
                uVar10 = uVar10 + iVar3;
                if (uVar9 == uVar11) goto LAB_00187dd0;
              }
              iVar1 = (uVar10 - iVar12) + 0xf;
              uVar6 = (undefined2)param_2;
              if (param_7 != 0) {
                if ((param_3 & 0x10000) == 0) {
                  do {
                    while (iVar13 = (int)uVar14, (uVar5 >> (ulong)(iVar1 - iVar13 & 0x1f) & 1) != 0)
                    {
                      *(undefined2 *)(param_6 + uVar14 * 2) = uVar6;
                      uVar14 = (ulong)(iVar13 + 1U);
                      if (iVar13 + 1U == uVar10) goto LAB_00187e58;
                    }
                    *(short *)(param_6 + uVar14 * 2) = (short)param_3;
                    uVar14 = (ulong)(iVar13 + 1U);
                  } while (iVar13 + 1U != uVar10);
                }
                else {
                  do {
                    if ((uVar5 >> (ulong)(iVar1 - (int)uVar14 & 0x1f) & 1) == 0) {
                      *(undefined2 *)(param_6 + uVar14 * 2) = *(undefined2 *)(param_7 + uVar14 * 2);
                    }
                    else {
                      *(undefined2 *)(param_6 + uVar14 * 2) = uVar6;
                    }
                    uVar2 = (int)uVar14 + 1;
                    uVar14 = (ulong)uVar2;
                  } while (uVar2 != uVar10);
                }
                goto LAB_00187e58;
              }
              if ((param_3 & 0x10000) == 0) {
                do {
                  if ((uVar5 >> (ulong)(iVar1 - (int)uVar14 & 0x1f) & 1) == 0) {
                    *(short *)(param_6 + uVar14 * 2) = (short)param_3;
                  }
                  else {
                    *(undefined2 *)(param_6 + uVar14 * 2) = uVar6;
                  }
                  uVar2 = (int)uVar14 + 1;
                  uVar14 = (ulong)uVar2;
                } while (uVar2 != uVar10);
                goto LAB_00187e58;
              }
              do {
                if ((uVar5 >> (ulong)(iVar1 - (int)uVar14 & 0x1f) & 1) != 0) {
                  *(undefined2 *)(param_6 + uVar14 * 2) = uVar6;
                }
                uVar2 = (int)uVar14 + 1;
                uVar14 = (ulong)uVar2;
              } while (uVar2 != uVar10);
              uVar9 = uVar9 + 1;
              uVar10 = uVar10 + iVar3;
            } while (uVar9 != uVar11);
          }
          goto LAB_00187dd0;
        }
        uVar16 = (ulong)((int)uVar16 + 1);
      } while (uVar9 != 0);
    }
  }
  else {
    uVar9 = (uint)*param_1;
    if (*param_1 != 0) {
      iVar4 = (int)((param_8 & 0xffffffff) >> 2);
      uVar11 = *(uint *)(current_font + 4);
      uVar15 = 0;
      uVar16 = 1;
      iVar8 = param_4;
      do {
        if (uVar9 != 10) goto LAB_00187cd0;
        uVar9 = (uint)param_1[uVar16];
        uVar15 = uVar15 + 1;
        param_5 = param_5 + uVar11;
        iVar8 = param_4;
        if (uVar9 == 0 && uVar15 < param_9) {
          do {
            uVar9 = 0x20;
LAB_00187cd0:
            uVar10 = *(uint *)puVar7;
            iVar3 = *(int *)(puVar7 + (long)(int)uVar9 * 4 + 0x2008);
            if (uVar11 != 0) {
              iVar12 = iVar8 + iVar4 * param_5;
              uVar9 = 0;
              do {
                uVar5 = *(ushort *)(puVar7 + (ulong)(iVar3 + uVar9) * 2 + 8);
                if (uVar10 != 0) {
                  uVar11 = 0;
                  do {
                    while ((uVar5 >> (ulong)(0xf - uVar11 & 0x1f) & 1) != 0) {
                      *(uint *)(param_6 + (ulong)(iVar12 + uVar11) * 4) =
                           ((uint)((param_2 & 0xffffffff) >> 5) & 0x3f) << 10 |
                           ((uint)((param_2 & 0xffffffff) >> 0xb) & 0x1f) << 0x13 |
                           ((uint)param_2 & 0x1f) << 3;
                      uVar11 = uVar11 + 1;
                      uVar10 = *(uint *)puVar7;
                      if (uVar10 <= uVar11) goto LAB_00187d24;
                    }
                    *(uint *)(param_6 + (ulong)(iVar12 + uVar11) * 4) =
                         ((uint)((param_3 & 0xffffffff) >> 5) & 0x3f) << 10 |
                         ((uint)((param_3 & 0xffffffff) >> 0xb) & 0x1f) << 0x13 |
                         ((uint)param_3 & 0x1f) << 3;
                    uVar11 = uVar11 + 1;
                    uVar10 = *(uint *)puVar7;
                  } while (uVar11 < uVar10);
LAB_00187d24:
                  uVar11 = *(uint *)(puVar7 + 4);
                }
                uVar9 = uVar9 + 1;
                iVar12 = iVar12 + iVar4;
              } while (uVar9 < uVar11);
            }
            iVar8 = iVar8 + uVar10;
            uVar9 = (uint)param_1[uVar16];
            uVar15 = uVar15 + 1;
          } while (uVar9 == 0 && uVar15 < param_9);
        }
        uVar16 = (ulong)((int)uVar16 + 1);
      } while (uVar9 != 0);
    }
  }
  return;
}

void print_string(undefined8 param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4)

{
  undefined4 uVar1;
  long lVar2;
  undefined4 param_5 = 0;
  lVar2 = get_screen_ptr(0);
  if ((lVar2 == 0) && (lVar2 = get_screen_ptr(1), lVar2 == 0)) {
    return;
  }
  uVar1 = get_screen_pitch_text(0);
  print_string_ext(param_1,param_2,param_3,param_4,param_5,lVar2,0,uVar1,0);
  return;
}

void platform_initialize_input(void);

void platform_print_code(char param_1, ulong param_2);

void platform_quit(void);

void platform_set_default_controls(undefined8 param_1, undefined8 param_2);

void platform_set_rumble_state(int param_1);

void process_arguments(long param_1, undefined4 param_2, char** param_3);

void process_cheat(long param_1, undefined8 param_2, uint param_3);

void process_cheats(undefined8 param_1, long param_2, undefined4 param_3);

void process_geometry(long param_1);

void process_geometry_commands(long param_1, int param_2);

#ifdef __GLIBC__
// 系统已经定义了这些 pthread 函数，使用系统版本
// int pthread_cond_init(pthread_cond_t __cond, pthread_condattr_t __cond_attr); // 注释掉，避免冲突
// int pthread_cond_signal(pthread_cond_t __cond); // 注释掉，避免冲突
// int pthread_cond_wait(pthread_cond_t __cond, pthread_mutex_t __mutex); // 注释掉，避免冲突
#else
int pthread_cond_init(pthread_cond_t __cond, pthread_condattr_t __cond_attr);

int pthread_cond_signal(pthread_cond_t __cond);

int pthread_cond_wait(pthread_cond_t __cond, pthread_mutex_t __mutex);
#endif // __GLIBC__

#ifdef __GLIBC__
// 系统已经定义了这些 pthread 函数，使用系统版本
// int pthread_mutex_init(pthread_mutex_t __mutex, pthread_mutexattr_t __mutexattr); // 注释掉，避免冲突
// int pthread_mutex_lock(pthread_mutex_t __mutex); // 注释掉，避免冲突
// int pthread_mutex_unlock(pthread_mutex_t __mutex); // 注释掉，避免冲突
#else
int pthread_mutex_init(pthread_mutex_t __mutex, pthread_mutexattr_t __mutexattr);

int pthread_mutex_lock(pthread_mutex_t __mutex);

int pthread_mutex_unlock(pthread_mutex_t __mutex);
#endif // __GLIBC__

int putchar(int __c);

#ifdef __GLIBC__
// 系统已经定义了 puts，使用系统版本
// int puts(char* __s); // 注释掉，避免冲突
#else
int puts(char* __s);
#endif // __GLIBC__

void qsort(void* __base, size_t __nmemb, size_t __size, __compar_fn_t __compar);

void queue_geometry_command(long param_1, uint param_2, undefined4 param_3);

void queue_geometry_command_packed_multi(long param_1, uint param_2, ulong param_3);

int queue_geometry_command_packed_multi_cycles(long param_1, uint param_2, ulong param_3);

void quit(long param_1);

undefined8 RARCloseArchive(RAROptions param_1);

CommandData * RAROpenArchiveEx(undefined8 param_1);

void RARProcessFile(void* param_1, int param_2, char param_3, char param_4);

ulong RARReadHeaderEx(void* param_1, char param_2);

void RARSetCallback(long param_1, undefined8 param_2, undefined8 param_3);

ssize_t read(int __fd, void* __buf, size_t __nbytes);

#ifdef __GLIBC__
// 系统已经定义了 readdir，使用系统版本
// dirent * readdir(DIR __dirp); // 注释掉，避免冲突（系统版本使用 DIR*）
#else
dirent * readdir(DIR __dirp);
#endif // __GLIBC__

void * realloc(void* __ptr, size_t __size);

void recompiler_entry(long param_1, undefined8 param_2);

int remap_address_region_low_memory(long param_1, long param_2, ulong param_3, uint param_4);

int remap_address_region_vram(long param_1, void* param_2, ulong param_3, uint param_4);

void remap_dtcm(long param_1, uint param_2, uint param_3);

int remap_file_pages(void* __start, size_t __size, int __prot, size_t __pgoff, int __flags);

void remap_itcm(long param_1, uint param_2);

void remap_palette_oam_deferred(long param_1);

void remap_palette_oam_direct(long param_1);

void remap_vram_body(long param_1, long param_2, uint param_3, uint param_4, int param_5);

void remap_wram(long param_1);

void remove_event(long param_1, ulong param_2);

#ifdef __GLIBC__
// 系统已经定义了 rename，使用系统版本
// int rename(char* __old, char* __new); // 注释掉，避免冲突
#else
int rename(char* __old, char* __new);
#endif // __GLIBC__

void render_polygon_1x(long param_1, long param_2, long param_3, uint param_4, uint param_5);

void render_polygon_4x(long param_1, long param_2, long param_3, uint param_4, uint param_5);

void render_polygon_load_texels_asm(undefined4 param_1, uint param_2, long param_3, int param_4);

void render_polygon_set_buffer32_asm(undefined4 param_1, undefined4 param_2, int param_3);

void render_polygon_set_buffer8_asm(undefined1 param_1, undefined1 param_2, int param_3);

void render_polygon_setup_edge_markers_c(long param_1, int param_2, uint param_3);

void render_polygon_setup_spans_asm_1x(byte param_1, int param_2);

void render_polygon_setup_spans_asm_4x(byte param_1, int param_2);

void render_polygon_setup_uv_interpolants_asm(long param_1, int param_2, int param_3, ulong param_4);

void render_scanline(long param_1, uint param_2, ulong param_3, long param_4);

int render_scanline_2d(undefined8 param_1, long param_2, ulong param_3, long param_4, int param_5);

int * render_scanline_3d(long param_1, ulong param_2);

void render_scanline_apply_windows(long param_1, uint param_2, uint param_3, uint param_4);

void render_scanline_bg(long param_1, long param_2, long param_3, uint param_4);

void render_scanline_capture_blended(long param_1, long param_2, long param_3, long param_4);

void render_scanline_capture_blended_3d(long param_1, long param_2, long param_3, long param_4);

void render_scanline_color_convert_direct_16_1x_asm(char param_1, undefined1 param_2);

void render_scanline_color_convert_direct_16_2x_asm(char param_1, char param_2, undefined1 param_3);

void render_scanline_color_convert_direct_32_1x_asm(char param_1, char param_2);

void render_scanline_color_convert_direct_32_2x_asm(char param_1, char param_2, char param_3);

void render_scanline_disable_blank_layers_asm(byte param_1, undefined4 param_2);

void render_scanline_expand_6bit_split_asm(char param_1, ushort param_2);

void render_scanline_horizontal_shift_3d(void* param_1, void* param_2, ulong param_3);

void render_sprite_check_isra_0(long param_1, long param_2);

void reset_backup(long param_1);

void reset_coprocessor(long param_1);

void reset_cpu(long param_1);

void reset_cpu_block(long param_1);

void reset_debug(long param_1);

void reset_dma(long param_1);

void reset_event_list(long param_1);

void reset_gamecard(long param_1);

void reset_geometry(long param_1);

void reset_input(long param_1);

void reset_ipc(long param_1);

void reset_memory(long *param_1);

void reset_rtc(long param_1, int param_2, time_t param_3);

void reset_spi_peripherals(long param_1);

void reset_spu(long param_1);

void reset_system(undefined8* param_1);

void reset_texture_cache(long param_1);

void reset_translation_cache(long param_1);

void reset_video(long* param_1);

void reset_video_2d(long param_1);

void reset_video_3d(void* param_1);

void rtc_store_savestate(undefined8 param_1, long param_2, uint param_3);

undefined8 rumble_pack_update(long param_1);

void save_config_file(long param_1, undefined8 param_2, int param_3);

undefined8 save_directory_config_file(long param_1, undefined8 param_2);

void save_state(ulong param_1, char param_2, char param_3, void* param_4, void* param_5);

void save_state_index(long param_1, undefined4 param_2, undefined8 param_3, undefined8 param_4);


void load_state_index(long param_1, undefined4 param_2, undefined8 param_3, undefined8 param_4, int param_5);
int savestate_index_timestamp(long param_1, undefined4 param_2);

void schedule_event(long param_1, uint param_2, ulong param_3);

void screen_copy16(ushort param_1, undefined4 param_2);

void screen_set_cursor_position(undefined4 param_1, undefined4 param_2, undefined4 param_3);

void screen_wait_for_vsync(void);
/*
void SDL_CaptureMouse(int param_1);

undefined8 SDL_CreateRenderer(undefined8 param_1, int param_2, uint param_3);

// SDL_CreateTexture 有两个声明，保留一个（可能是函数重载）
undefined8 SDL_CreateTexture(undefined8 param_1, uint param_2, int param_3, int param_4);
// undefined8 SDL_CreateTexture(undefined8 param_1, uint param_2, int param_3, int param_4, int param_5); // 注释掉重复声明

undefined8 SDL_CreateWindow(char* param_1, uint param_2, uint param_3, int param_4, int param_5, uint param_6);

void SDL_Delay(void);

void SDL_DestroyTexture(void);

int SDL_GetCurrentDisplayMode(int param_1, void* param_2);

void SDL_GetError(void);

void SDL_GetKeyName(void);

void SDL_GetModState(void);

void SDL_GetTicks(void);

void SDL_HapticOpen(void);

void SDL_HapticOpenFromJoystick(void);

void SDL_HapticRumbleInit(void);

void SDL_HapticRumblePlay(void);

void SDL_HapticRumbleStop(void);

void SDL_HapticRumbleSupported(void);

void SDL_Init(void);

void SDL_JoystickEventState(void);

void SDL_JoystickName(void);

void SDL_JoystickOpen(void);

void SDL_LockTexture(void);

void SDL_memset(void);

void SDL_NumHaptics(void);

void SDL_NumJoysticks(void);

void SDL_OpenAudio(void);

void SDL_PauseAudio(void);

void SDL_PollEvent(void);

void SDL_RenderClear(void);

void SDL_RenderCopy(void);

void SDL_RenderGetLogicalSize(void);

void SDL_RenderPresent(void);

int SDL_RenderSetLogicalSize(undefined8 param_1, int param_2, undefined8 param_3);

int SDL_SetHint(char* param_1, char* param_2);

int SDL_SetRenderDrawBlendMode(undefined8 param_1, int param_2);

void SDL_SetRenderDrawColor(undefined8 param_1, byte param_2, byte param_3, byte param_4, byte param_5);

int SDL_SetTextureBlendMode(undefined8 param_1, int param_2);

int SDL_SetWindowFullscreen(undefined8 param_1, uint param_2);

void SDL_SetWindowSize(undefined8 param_1, int param_2, int param_3);

void SDL_UnlockTexture(void);

int SDL_UpdateTexture(undefined8 param_1, void* param_2, void* param_3, int param_4);
*/

void select_exit_current_menu(long param_1, long param_2);

void set_active_cheats(long param_1);

void set_debug_mode(long param_1, undefined1 param_2);

void set_font_narrow(void);

void set_font_narrow_small(void);

void set_font_wide(void)

{
  current_font = font_b;
  return;
}

void set_screen_hires_mode(uint param_1, uint param_2);

void set_screen_menu_off(void);

void set_screen_menu_on(void);

void set_screen_orientation(undefined4 param_1)

{
  //DAT_040315c4._4_4_ = param_1;
  //DAT_040315d4._0_4_ = 1;
  return;
}

void set_screen_swap(undefined4 param_1)

{
  //DAT_040315cc._0_4_ = param_1;
  return;
}

int shm_open(char* __name, int __oflag, mode_t __mode);

int shm_unlink(char* __name);

byte * skip_to_whitespace(byte param_1);

byte * skip_whitespace(byte param_1);

#ifdef __GLIBC__
// 系统已经定义了 snprintf，使用系统版本
// int snprintf(char* __s, size_t __maxlen, char* __format, ...); // 注释掉，避免冲突
#else
int snprintf(char* __s, size_t __maxlen, char* __format, ...);
#endif // __GLIBC__

void spi_peripherals_store_savestate(long param_1, long param_2, uint param_3);

void spu_adpcm_decode_block(long param_1);

void spu_fake_microphone_start(long param_1);

void spu_fake_microphone_stop(long param_1);

void spu_load_fake_microphone_data(long param_1, char param_2);

void spu_render_capture(long param_1, undefined8 param_2, int param_3, uint param_4);

void spu_render_samples(long param_1, undefined8 param_2, int param_3);

void spu_store_savestate(long param_1, long param_2);

void spu_update_channel_settings(long param_1, long param_2);

void start_frame(long param_1);

#ifdef __GLIBC__
// 系统已经定义了这些字符串函数，使用系统版本
// int strcasecmp(char __s1, char __s2); // 注释掉，避免冲突
// char * strchr(char* __s, int __c); // 注释掉，避免冲突
// int strcmp(char __s1, char __s2); // 注释掉，避免冲突
// char * strcpy(char* __dest, char* __src); // 注释掉，避免冲突
// size_t strlen(char* __s); // 注释掉，避免冲突
#else
int strcasecmp(char __s1, char __s2);

char * strchr(char* __s, int __c);

int strcmp(char __s1, char __s2);

char * strcpy(char* __dest, char* __src);

size_t strlen(char* __s);
#endif // __GLIBC__

#ifdef __GLIBC__
// 系统已经定义了这些字符串函数，使用系统版本
// int strncasecmp(char __s1, char __s2, size_t __n); // 注释掉，避免冲突
// int strncmp(char __s1, char __s2, size_t __n); // 注释掉，避免冲突
// char * strncpy(char* __dest, char* __src, size_t __n); // 注释掉，避免冲突
#else
int strncasecmp(char __s1, char __s2, size_t __n);

int strncmp(char __s1, char __s2, size_t __n);

char * strncpy(char* __dest, char* __src, size_t __n);
#endif // __GLIBC__

char * strncpyz(char param_1, char param_2, ulong param_3);

#ifdef __GLIBC__
// 系统已经定义了 strrchr，使用系统版本
// char * strrchr(char* __s, int __c); // 注释掉，避免冲突
#else
char * strrchr(char* __s, int __c);
#endif // __GLIBC__

char * strstr(char* __haystack, char* __needle);

#ifdef __GLIBC__
// 系统已经定义了这些函数，使用系统版本
// long strtol(char* __nptr, char* __endptr, int __base); // 注释掉，避免冲突
// ulong strtoul(char* __nptr, char* __endptr, int __base); // 注释掉，避免冲突
#else
long strtol(char* __nptr, char* __endptr, int __base);

ulong strtoul(char* __nptr, char* __endptr, int __base);
#endif // __GLIBC__

#ifdef __GLIBC__
// 系统已经定义了 strtoull，使用系统版本
// ulonglong strtoull(char* __nptr, char* __endptr, int __base); // 注释掉，避免冲突
#else
ulonglong strtoull(char* __nptr, char* __endptr, int __base);
#endif // __GLIBC__

void system_frame_sync(long param_1);

void system_store_savestate(undefined8 param_1, long param_2, undefined4 param_3);

void * SzAlloc(undefined8 param_1, size_t param_2);

void SzAr_Free(undefined8 param_1, long param_2);

void SzArEx_Free(undefined8 param_1, long param_2);

void SzArEx_GetFileNameUtf16(long param_1, long param_2, undefined8 param_3);

long SzArEx_GetFolderStreamPos(long param_1, ulong param_2, int param_3);

void SzArEx_Init(undefined8 param_1);

int SzArEx_Open(long param_1, long param_2, undefined8 param_3, undefined8 param_4);

void SzFolder_Free(long param_1, long param_2);

undefined8 SzFolder_GetUnpackSize(long param_1);

void SzFree(undefined8 param_1, void* param_2);

undefined8 SzReadBoolVector2(long param_1, long param_2, long param_3, undefined8 param_4);

undefined8 SzReadNumber(long param_1, ulong param_2);

int texture_cache_build_pixel(uint param_1);

uint texture_cache_build_pixel_custom_alpha(uint param_1, int param_2);

uint texture_cache_build_pixel_embedded_alpha(ulong param_1);

void texture_cache_convert_4bpp_asm(byte param_1, byte param_2, int param_3);

void texture_cache_create(uint param_1, long param_2, uint param_3, int param_4);

uint * texture_cache_lookup(long param_1, uint param_2, uint param_3);

#ifdef __GLIBC__
// 系统已经定义了 time，使用系统版本
// time_t time(time_t __timer); // 注释掉，避免冲突
#else
time_t time(time_t __timer);
#endif // __GLIBC__

void touchscreen_set_position(long param_1, short param_2, short param_3);

void translation_cache_flush_alternate(long param_1);

void translation_cache_flush_itcm(long param_1);

void translation_cache_flush_main(long param_1);

void * un7z_file(undefined8 param_1, char param_2, uint param_3, long param_4);

void unescape_str(char param_1, long param_2, uint param_3, int param_4);

int uninitialize_memory(long param_1);

#ifdef __GLIBC__
// 系统已经定义了 unlink，使用系统版本
// int unlink(char* __name); // 注释掉，避免冲突
#else
int unlink(char* __name);
#endif // __GLIBC__

void unmap_memory_page_region(long param_1, ulong param_2, int param_3);

void unmap_memory_page_region_direct(long param_1, ulong param_2, int param_3);

void unmap_vram_page_region_arm9(long param_1, uint param_2, uint param_3, uint param_4);

void * unrar_file(undefined8 param_1, char param_2, uint param_3, char param_4);

void * unzip_file(char param_1, undefined8 param_2, uint param_3, char param_4);

int unzip_find_file_entry(int param_1, char param_2, undefined8 param_3, uint param_4);

void update_frame(long param_1);

void update_frame_3d(long param_1);

void update_frame_3d_1x(long param_1, int param_2);

void update_frame_3d_4x(long param_1, int param_2);

void update_frame_geometry(long param_1);

void update_input(long param_1);

void update_screen(ulong param_1);

void update_screen_menu(void);

void update_screens(void);

void update_spu(long param_1);

int update_texture_cache(long param_1);

undefined8 Utf16_To_Utf8Buf(long param_1, long param_2, long param_3);

void video_2d_map_bg_direct_layers(long param_1);

void video_2d_render_scanlines(undefined8 param_1, uint param_2, uint param_3, undefined8 param_4);

void video_2d_reorder_layers(long param_1);

void video_2d_reorder_obj(long param_1);

void video_2d_set_bg_control(long param_1, uint param_2, uint param_3);

void video_2d_set_display_control(long param_1, uint param_2);

void video_2d_store_savestate(long param_1, long param_2, uint param_3);

void video_2d_update_bg_mode(long param_1);

void video_3d_bin_polygons_1x(long param_1, long param_2, uint param_3, long param_4, uint param_5);

void video_3d_bin_polygons_4x(long param_1, long param_2, uint param_3, long param_4, uint param_5);

int video_3d_finish_rendering(long param_1);

void video_3d_render_bins_1x(long param_1);

void video_3d_render_bins_4x(long param_1);

void video_3d_resolve_bin_asm_1x(uint param_1, uint param_2);

void video_3d_resolve_bin_asm_4x(uint param_1, uint param_2);

void video_3d_resolve_bin_edge_mark_1x(void* param_1, long param_2, uint param_3);

void video_3d_resolve_bin_edge_mark_4x(void* param_1, long param_2, uint param_3);

void video_3d_resolve_bin_edge_mark_fog_alpha_1x(void* param_1, long param_2, uint param_3);

void video_3d_resolve_bin_edge_mark_fog_alpha_4x(void* param_1, long param_2, uint param_3);

void video_3d_resolve_bin_edge_mark_fog_alpha_gaps_1x(long param_1);

void video_3d_resolve_bin_edge_mark_fog_alpha_gaps_4x(long param_1);

void video_3d_resolve_bin_edge_mark_fog_full_1x(void* param_1, long param_2, uint param_3);

void video_3d_resolve_bin_edge_mark_fog_full_4x(void* param_1, long param_2, uint param_3);

void video_3d_resolve_bin_edge_mark_fog_full_gaps_1x(long param_1);

void video_3d_resolve_bin_edge_mark_fog_full_gaps_4x(long param_1);

void video_3d_resolve_bin_edge_mark_gaps_1x(long param_1);

void video_3d_resolve_bin_edge_mark_gaps_4x(long param_1);

void video_3d_resolve_bin_fog_alpha_1x(long param_1, long param_2);

void video_3d_resolve_bin_fog_alpha_4x(long param_1, long param_2);

void video_3d_resolve_bin_fog_full_1x(long param_1, long param_2);

void video_3d_resolve_bin_fog_full_4x(long param_1, long param_2);

void video_3d_start_rendering();

ulong video_render_scanlines(long param_1, int param_2);

void video_store_savestate(long param_1, long param_2, undefined4 param_3);

#ifdef __GLIBC__
// 系统已经定义了这些宽字符函数，使用系统版本
// wchar_t * wcscpy(wchar_t __dest, wchar_t __src); // 注释掉，避免冲突
// size_t wcslen(wchar_t __s); // 注释掉，避免冲突
// wchar_t * wcsncpy(wchar_t __dest, wchar_t __src, size_t __n); // 注释掉，避免冲突
#else
wchar_t * wcscpy(wchar_t __dest, wchar_t __src);

size_t wcslen(wchar_t __s);

wchar_t * wcsncpy(wchar_t __dest, wchar_t __src, size_t __n);
#endif // __GLIBC__

void xml_parse_line(FILE* param_1, char param_2, char param_3);

// Lua 函数声明

int luaL_loadfilex(void* L, const char* filename, const char* mode);
int lua_pcallk(void* L, int nargs, int nresults, int errfunc, int ctx, void* k);
void lua_getglobal(void* L, const char* name);
void lua_pushstring(void* L, const char* s);


#ifdef __cplusplus
}
#endif

#endif // DRASTIC_FUNCTIONS_H
